apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: priih8sq3-nodejs-gitops
  description: This is GitOps manifest for priih8sq3-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=priih8sq3-nodejs
    backstage.io/kubernetes-id: priih8sq3-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: priih8sq3-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:priih8sq3-nodejs
