apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: priih8sq3-nodejs
  janus-idp.io/tekton: priih8sq3-nodejs
  backstage.io/kubernetes-id: priih8sq3-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: priih8sq3-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
